/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import inheritance.Restaurant;
import org.junit.Test;
import static org.junit.Assert.*;


public class LibraryTest {


}
