/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.Arrays;
import java.util.Random;
//package basiclibrary;

public class Library {
    public static void main(String[] args){
        int n = 4; //number of rolls
        int m = 8;
        int o = 12;
//        int sides = 6; //number of sides on the dice
        roll(n);
        roll(m);
        roll(o);

    }
    public static int[] roll(int value) {
        Random rand = new Random();
        int[] rollingArray = new int[value]; //array of roll outcomes
        for (int i = 0; i < rollingArray.length; i++) {
            int outcome = rand.nextInt(7)+1;
            rollingArray[i] = outcome;
        }
        System.out.println(Arrays.toString(rollingArray));
        return rollingArray;
    }
}

//